// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Security.Claims;
using LostnFound.Models;
using Microsoft.EntityFrameworkCore;

namespace _.Models;

public partial class DBproductsContext : DbContext
{
    public DBproductsContext(DbContextOptions<DBproductsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Item> Items { get; set; }
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<UserClaim> UserClaim { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__users__B9BE370F6A081DFB");

            entity.ToTable("users");

            entity.HasIndex(e => e.Email, "UQ__users__AB6E6164A133BF1B").IsUnique();

            entity.Property(e => e.UserId)
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("user_id");
            entity.Property(e => e.CountryCode)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasColumnName("country_code");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("first_name");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("last_name");
            entity.Property(e => e.OAuthId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("oauth_id");
            entity.Property(e => e.OAuthProvider)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("oauth_provider");
            entity.Property(e => e.PasswordHashed)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("password_hashed");
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("phone_number");
            entity.Property(e => e.ProfilePictureUrl)
              .HasMaxLength(255)
              .IsUnicode(false)
              .HasColumnName("profile_picture");
        });


        modelBuilder.Entity<Item>(entity =>
        {
            entity.HasKey(e => e.ItemId).HasName("PK__Items__727E83EB238D617F");

            entity.Property(e => e.ItemId).HasColumnName("ItemID");
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.ImagePath)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ItemName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ItemType)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Location)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("UserID");
        });

        modelBuilder.Entity<UserClaim>(entity =>
        {
            entity.HasKey(e => e.ClaimID);

            entity.Property(e => e.ClaimStatus)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.ClaimantID)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.ClaimDate)
                .HasColumnType("date")
                .HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.Item)
                .WithMany()
                .HasForeignKey(d => d.ItemID)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Claims_Items");

            entity.HasOne(d => d.Claimant)
                .WithMany()
                .HasForeignKey(d => d.ClaimantID)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_Claims_Users");
        });


        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}