// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LostnFound.Models;

namespace _.Models;

public partial class Item
{
    public int ItemId { get; set; }

    public string UserId { get; set; }

    public string ItemName { get; set; }

    public string Description { get; set; }

    public DateOnly DateReported { get; set; }

    public string Location { get; set; }

    public string ImagePath { get; set; }

    public string ItemType { get; set; }

    public string Status { get; set; }
    public virtual User User{ get; set; }
}