// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _.Models;

public partial class User
{
    public string UserId { get; set; }

    public string Email { get; set; }

    public string OauthProvider { get; set; }

    public string OauthId { get; set; }

    public string PasswordHashed { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string CountryCode { get; set; }

    public string PhoneNumber { get; set; }
}